### ISSUE TITLE
Transfer Popup Not loading (white/blank popup) - All devices/setups

### ISSUE THREAD

**Issue by telos-justin** [telosnetwork/telos-keycat#13]
Popup happening but nothing to view. Seems on and off, finding it hard to figure out when/why it is happening.

**Comment by telos-justin** [comment]
white popup screen of death.

![ezgif-7-6c1dbab1e430](https://user-images.githubusercontent.com/65044262/92978837-cd269500-f445-11ea-9d5e-1ff3c15ff870.gif)

**Comment by telos-justin** [comment]
Could be wrong but it appears to be happening much more often in Safari on both iOS and Desktop

**Comment by telos-justin** [comment]
FROM SAFARI DESKTOP.. CONSOLE for the blank/white transfer window

[Error] The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.
[Log] Welcome 1e89b45 (772723ebf9a0b501c278.js, line 284)
[Error] TypeError: null is not an object (evaluating 'Object.keys(e)')
	el (772723ebf9a0b501c278.js:336:82645)
	(anonymous function) (772723ebf9a0b501c278.js:336:89756)
	di (772723ebf9a0b501c278.js:336:48812)
	il (772723ebf9a0b501c278.js:336:83841)
	pu (772723ebf9a0b501c278.js:336:101502)
	pu
	(anonymous function) (772723ebf9a0b501c278.js:9:4088)
	du (772723ebf9a0b501c278.js:336:97974)
	Jl (772723ebf9a0b501c278.js:336:94128)
	Jl
	(anonymous function) (772723ebf9a0b501c278.js:336:45570)
	(anonymous function) (772723ebf9a0b501c278.js:9:4088)
	Qo (772723ebf9a0b501c278.js:336:45516)
	F (772723ebf9a0b501c278.js:9:3027)
	(anonymous function) (772723ebf9a0b501c278.js:9:1783)
[Error] TypeError: null is not an object (evaluating 'Object.keys(e)')
	el (772723ebf9a0b501c278.js:336:82645)
	(anonymous function) (772723ebf9a0b501c278.js:336:89423)
	di (772723ebf9a0b501c278.js:336:48812)
	il (772723ebf9a0b501c278.js:336:83993)
	pu (772723ebf9a0b501c278.js:336:101502)
	pu
	(anonymous function) (772723ebf9a0b501c278.js:9:4088)
	du (772723ebf9a0b501c278.js:336:97974)
	Jl (772723ebf9a0b501c278.js:336:94128)
	Jl
	(anonymous function) (772723ebf9a0b501c278.js:336:45570)
	(anonymous function) (772723ebf9a0b501c278.js:9:4088)
	Qo (772723ebf9a0b501c278.js:336:45516)
	F (772723ebf9a0b501c278.js:9:3027)
	(anonymous function) (772723ebf9a0b501c278.js:9:1783)
[Error] TypeError: null is not an object (evaluating 'Object.keys(e)')
	(anonymous function) (772723ebf9a0b501c278.js:9:1860)

**Comment by telos-justin** [comment]
<img width="1071" alt="Screen Shot 2020-09-12 at 4 54 22 pm" src="https://user-images.githubusercontent.com/65044262/93007043-b8ff9800-f518-11ea-981c-1920dfbe68a8.png">

**Comment by telos-justin** [comment]
Console from brave
<img width="1438" alt="Screen Shot 2020-09-12 at 5 01 40 pm" src="https://user-images.githubusercontent.com/65044262/93007121-c6695200-f519-11ea-8428-efa8ca519753.png">

**Comment by smilingkylan** [comment]
Try again when you get a chance @telos-justin

**Comment by telos-justin** [comment]
Having trouble replicating! Looking good! I think we should close this for now and re-open it if it comes back up again. *Fingers crossed*
