### ISSUE TITLE
Transfer popup not closing on execution of transfer -  iOS - Chrome

### ISSUE THREAD

**Issue by telos-justin** [telosnetwork/telos-keycat#9]
Tested on:
https://template.telos.net/transfer

Transfer occurs as planned but window does not close leaving user to continually submit transaction.

Software:
 iOS - Chrome and Safari

**Comment by telos-justin** [comment]
Made a mistake, this issue is also on Safari.

**Comment by smilingkylan** [comment]
Close button now added for manual window-closing

**Comment by smilingkylan** [comment]
Maybe we should add a success message and let people know they can close that window if they'd like

**Comment by telos-justin** [comment]
We may need but the success message is currently in dapp ui so maybe not necessarily so lets hold off for now. 

Just to clarify the close button is mainly for if a user wants to cancel the transaction. They might see something that doesnt look like in the transfer window. :-)

Anyway lets close this tentatively for now as i haven't seen it re-occur since your last change.
